### ISSUE TITLE
Update to Tailwind v2

### ISSUE THREAD

**Issue by ecklf** [ecklf/tailwindcss-figma-kit#11]
Tailwind v2 is coming out today. I'll update the color scheme and adjust the components accordingly.

Since adding the colors as a preview by hand is quite a tedious process, I'll be integrating something to automate it in my Figma plugin.

- [x] Default Colors
- [x] Components
- [ ] Spacing
- [ ] Container
- [ ] New Plugin features

**Comment by kylewetton** [comment]
I'm wondering if you'd be willing to do a little side feature while you're upgrading this, I use this kit extensively, one thing that I always find myself doing is creating spacing as squares. I never feel like I need to know if spacing 10 is the Y or X, but I'd much rather have less spacers and just have a 10 square which can be used either for Y or X, it'll cut down the kit component size and make it easier to reason about which spacer you're choosing.
